"""Application persistence ports; no SQL or backend types cross this boundary."""

from contextlib import AbstractContextManager
from typing import Protocol

from sdd_core.models import Result, Run, Transition, Workflow
from sdd_core.runtime_ports import RuntimeRecords


class Conflict(ValueError):
    pass


class UnitOfWork(RuntimeRecords, Protocol):
    def run(self, identifier: str) -> Run: ...
    def apply(self, before: Run, transition: Transition) -> Run: ...
    def command(self, identifier: str) -> tuple[str, str] | None: ...
    def save_command(self, identifier: str, request: str, response: str) -> None: ...
    def location(self, identifier: str) -> tuple[str, str]: ...
    def policy(self, workspace: str) -> tuple[str, ...]: ...
    def dependencies(self, identifier: str) -> tuple[Run, ...]: ...
    def active_claims(self) -> tuple[tuple[str, str], ...]: ...
    def unfinished_claims(self, identifier: str) -> tuple[str, ...]: ...
    def results(self, identifier: str) -> tuple[Result, ...]: ...
    def receipt(self, attempt: str) -> tuple[str, str] | None: ...
    def save_result(self, attempt: str, fingerprint: str, document: str) -> None: ...
    def effect_status(self, attempt: str, status: str) -> None: ...


class StateStore(Protocol):
    def unit(self) -> AbstractContextManager[UnitOfWork]: ...
    def workflow(self, identifier: str) -> Workflow: ...
    def get(self, identifier: str) -> Run: ...
    def create(
        self,
        run: Run,
        workspace: str,
        context: str,
        claim: str,
        now: float,
        dependencies: tuple[str, ...] = (),
    ) -> Run: ...


class Workspace(Protocol):
    def resolve(self, path: str) -> str: ...
    def overlaps(self, left: str, right: str) -> bool: ...
    def normalize(self, run_id: str, result: Result, workspace: str) -> Result: ...
    def verify(self, result: Result, workspace: str, revision: str) -> None: ...
