"""Durable runtime records. Implementations participate in the same state transaction."""

from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class EffectRecord:
    id: str
    run_id: str
    kind: str
    status: str
    workspace: str
    pid: int | None = None
    created: float | None = None
    host_nonce: str | None = None
    receipt: str | None = None
    external: bool = False


class RuntimeRecords(Protocol):
    def bind_handler(self, run_id: str, handler: str, manifest: str) -> None: ...
    def context(self, run_id: str) -> str: ...
    def recent_results(self, run_id: str, limit: int) -> tuple[str, ...]: ...
    def effect(self, attempt: str) -> EffectRecord: ...
    def effects(self, statuses: tuple[str, ...]) -> tuple[EffectRecord, ...]: ...
    def claim_host(self, attempt: str, packet: str, nonce: str) -> None: ...
    def host_started(self, attempt: str, nonce: str, pid: int, created: float) -> None: ...
    def bind_execution(self, run_id: str, attempt: str, backend: str, document: str) -> None: ...
    def execution(self, attempt: str) -> tuple[str, str] | None: ...
    def runnable(self) -> tuple[str, ...]: ...
    def last_transition(self) -> float | None: ...
    def bind_portfolio(self, identifier: str, document: str) -> None: ...
    def portfolio(self, identifier: str) -> str | None: ...
    def set_policy(self, workspace: str, mandatory: tuple[str, ...]) -> None: ...
